import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import TailwindHeader from "@/components/TailwindHeader";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/Footer";

const notoSansJp = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={notoSansJp.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <header>
                        <Header />
                        {/* <TailwindHeader /> */}
                    </header>
                    <main>
                        {children}
                    </main>
                    <footer>
                        <Footer />
                    </footer>
                </ThemeProvider>
            </body>
        </html>
    );
}
